name: Infraestructures
on: 
    push: 
        branches:
            -	main

jobs:
    check:
        runs-on: ubuntu-latest
        
        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Run Terraform Validate
                run: |
                    terraform validate
                    echo "estoy en actions"

    deploy:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
        uses: actions/checkout@v3

        - name: Setup Terraform
        run: terraform init

        - name: Apply Terraform
        run: |
          terraform apply -auto-approve
          echo "Deployment completed successfully!"
    
    
